version: '3.8'

services:
  ethduties:
    image: ghcr.io/shayanb/ethduties:latest
    container_name: ethduties
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - SERVER_URL=${SERVER_URL}
    networks:
      - ethduties-network
    volumes:
      # Optional: Mount for persistent data if needed
      - ethduties-data:/app/data
    labels:
      # Portainer labels
      - "io.portainer.accesscontrol.public"
      # Auto-update with Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik labels for reverse proxy (optional)
      - "traefik.enable=true"
      - "traefik.http.routers.ethduties.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.ethduties.entrypoints=websecure"
      - "traefik.http.routers.ethduties.tls=true"
      - "traefik.http.routers.ethduties.tls.certresolver=letsencrypt"
      - "traefik.http.services.ethduties.loadbalancer.server.port=3000"

volumes:
  ethduties-data:

networks:
  ethduties-network:
    external: true